<?php
return [
    'login' => [
        'type' => 2,
    ],
    'authorization' => [
        'type' => 2,
    ],
    'logout' => [
        'type' => 2,
    ],
    'error' => [
        'type' => 2,
    ],
    'index' => [
        'type' => 2,
    ],
    'view' => [
        'type' => 2,
    ],
    'update' => [
        'type' => 2,
    ],
    'delete' => [
        'type' => 2,
    ],
    'full-delete' => [
        'type' => 2,
    ],
    'additional-delete' => [
        'type' => 2,
    ],
    'bulk-delete' => [
        'type' => 2,
    ],
    'create' => [
        'type' => 2,
    ],
    'comment-create' => [
        'type' => 2,
    ],
    'create-part' => [
        'type' => 2,
    ],
    'nomenclature-list' => [
        'type' => 2,
    ],
    'get-nomenclature' => [
        'type' => 2,
    ],
    'change-order-status' => [
        'type' => 2,
    ],
    'get-order-statuses' => [
        'type' => 2,
    ],
    'get-main-order-status' => [
        'type' => 2,
    ],
    'file-upload' => [
        'type' => 2,
    ],
    'file-remove' => [
        'type' => 2,
    ],
    'manager-view' => [
        'type' => 2,
    ],
    'actions-view' => [
        'type' => 2,
    ],
    'creator-view' => [
        'type' => 2,
    ],
    'manager-nomenclature' => [
        'type' => 2,
    ],
    'tech-nomenclature' => [
        'type' => 2,
    ],
    'request-details' => [
        'type' => 2,
    ],
    'get-measures' => [
        'type' => 2,
    ],
    'editable' => [
        'type' => 2,
    ],
    'update-detail' => [
        'type' => 2,
    ],
    'files-upload' => [
        'type' => 2,
    ],
    'guest' => [
        'type' => 1,
        'ruleName' => 'userGroup',
        'children' => [
            'login',
            'authorization',
        ],
    ],
    'change-china-status' => [
        'type' => 2,
    ],
    'change-main-order-status' => [
        'type' => 2,
    ],
    'change-additional-order-status' => [
        'type' => 2,
    ],
    'get-statuses-color' => [
        'type' => 2,
    ],
    'get-additional-photo' => [
        'type' => 2,
    ],
    'get-image-url' => [
        'type' => 2,
    ],
    'bulkdelete' => [
        'type' => 2,
    ],
    'clear-detail' => [
        'type' => 2,
    ],
    'backup' => [
        'type' => 2,
    ],
    'generate-own-vendor-code' => [
        'type' => 2,
    ],


    'user' => [
        'type' => 1,
        'ruleName' => 'userGroup',
        'children' => [
            'guest',
            'login',
            'authorization',
            'logout',
            'error',
            'index',
            'view',
//            'create',
//            'create-part',
            'nomenclature-list',
            'get-nomenclature',
//            'change-order-status',
            'get-order-statuses',
            'get-main-order-status',
//            'file-upload',
//            'file-remove',
//            'comment-create',
            'manager-view',
            'actions-view',
            'creator-view',
            'manager-nomenclature',
            'tech-nomenclature',
            'request-details',
            'get-measures',
//            'editable',
//            'update-detail',
//            'files-upload',
//            'change-china-status',
//            'change-main-order-status',
//            'change-additional-order-status',
            'get-statuses-color',
            'get-additional-photo',
            'get-image-url',
        ],
    ],
    'manager' => [
        'type' => 1,
        'ruleName' => 'userGroup',
        'children' => [
            'update',
            'guest',
            'login',
            'authorization',
            'logout',
            'error',
            'index',
            'view',
            'additional-delete',
            'create',
            'create-part',
            'nomenclature-list',
            'get-nomenclature',
            'change-order-status',
            'get-order-statuses',
            'get-main-order-status',
            'file-upload',
            'file-remove',
            'comment-create',
            'manager-view',
            'actions-view',
            'creator-view',
            'manager-nomenclature',
            'tech-nomenclature',
            'request-details',
            'get-measures',
            'editable',
            'update-detail',
            'files-upload',
            'change-china-status',
            'change-main-order-status',
            'change-additional-order-status',
            'get-statuses-color',
            'get-additional-photo',
            'get-image-url',
            'delete',
        ],
    ],
    'administrator' => [
        'type' => 1,
        'ruleName' => 'userGroup',
        'children' => [
            'guest',
            'user',
            'manager',
            'tech_specialist',
            'login',
            'authorization',
            'update',
            'delete',
            'full-delete',
            'additional-delete',
            'bulk-delete',
            'create',
            'create-part',
            'nomenclature-list',
            'get-nomenclature',
            'change-order-status',
            'get-order-statuses',
            'get-main-order-status',
            'file-upload',
            'file-remove',
            'comment-create',
            'manager-view',
            'actions-view',
            'creator-view',
            'manager-nomenclature',
            'tech-nomenclature',
            'request-details',
            'get-measures',
            'editable',
            'update-detail',
            'files-upload',
            'change-main-order-status',
            'change-additional-order-status',
            'get-statuses-color',
            'get-additional-photo',
            'get-image-url',
            'bulkdelete',
            'clear-detail',
            'backup',
            'generate-own-vendor-code',
        ],
    ],
    'tech_specialist' => [
        'type' => 1,
        'ruleName' => 'userGroup',
        'children' => [
            'update',
            'guest',
            'login',
            'authorization',
            'logout',
            'error',
            'index',
            'view',
            'additional-delete',
            'create',
            'create-part',
            'nomenclature-list',
            'get-nomenclature',
            'change-order-status',
            'get-order-statuses',
            'get-main-order-status',
            'file-upload',
            'file-remove',
            'comment-create',
            'manager-view',
            'actions-view',
            'creator-view',
            'manager-nomenclature',
            'tech-nomenclature',
            'request-details',
            'get-measures',
            'editable',
            'update-detail',
            'files-upload',
            'change-china-status',
            'change-main-order-status',
            'change-additional-order-status',
            'get-statuses-color',
            'get-additional-photo',
            'get-image-url',
            'clear-detail',
        ],
    ],
];
